### ISSUE TITLE
Gracefully handle listing NFT with invalid params

### ISSUE THREAD

**Issue by jcr7467** [jcr7467/NFTMarket#161]
right now, if you open up an NFT to list it for sale, but the sale value is 0, and hit 'list for sale', it will throw an error saying that the write function is invalid. It is invalid because 0 is not a valid value to list for sale, but we want to just log this error, and show an alert to the user that you can't list an NFT for 0

![Screenshot 2023-04-05 at 12 17 49 AM](https://user-images.githubusercontent.com/25701682/230008916-cb5e316a-4c49-4f37-a1e7-9f1a2839a724.png)
![Screenshot 2023-04-05 at 12 18 00 AM](https://user-images.githubusercontent.com/25701682/230008973-fde03d53-5d2a-4509-b3af-7871c325a151.png)

**Comment by ntjoar** [comment]
Question on this: do we want to do alert messages or do what we did in #165 and add on the fact that we disable the listing unless they give us a valid value?

**Comment by jcr7467** [comment]
Hmmm yeah let’s go with the one you implemented 😍
